module.exports.projectsList = [
  {
    id: 10,
    featured: true,
    name: "Skanr",
    description:
      "A Cross-Platform Mobile App for getting place details using only the native camera. The app uses the Google Places API in combinations with Vision API for image analysis",
    techStack: [
      { name: "React-Native" },
      { name: "Redux" },
      { name: "Tailwindcss" },
      { name: "Expo" },
      { name: "Google Cloud Services" },
      { name: "Places API" },
      { name: "Vision AI" },
      { name: "Firebase" },
      { name: "Jest" },
    ],
    livesite: "https://expo.dev/@sohailgsais/skanr-app",
    demo: false,
    githubRepo: "https://github.com/SohailMG/skanr",
    image: "/images/skanrApp.png",
  },
  {
    id: 12,
    featured: true,
    name: "Covid Trakr",
    description:
      "A Covid-19 data visualiser using the OpenData RESTAPI in combination with various AWS(Amazon Web Services) to provide serverless functionality such as ApiGateway,lambda function as well as machine learning services such as sagemaker to perform future predictions on covid cases along with sentiment analysis on twitter posts using twitter api",
    techStack: [
      { name: "Typescript" },
      { name: "Reactjs" },
      { name: "Tailwindcss" },
      { name: "AWS" },
      { name: "Java" },
      { name: "Spring" },
      { name: "Hibernate" },
      { name: "Maven" },
      { name: "JSoup" },
    ],
    livesite: "https://cst3130-covid-trakr.s3.amazonaws.com/index.html",
    demo: false,
    githubRepo: "https://github.com/SohailMG/covid-tracker",
    image: "/images/covid-trakr.png",
  },
  {
    id: 4,
    featured: true,
    name: "Price Finder",
    description:
      "This is a university project where I implemented a price comparison website on Yeezys,  using Java with Jsoup and Selenium to scrape the data from each website. Selenium was used for some scrapers in cases . I used Spring framework with annotations to manage classes. The data scraped was stored in an SQL database using Hibernate. Threads were used for each scraper to help run scraper simultaneously without interruptions where each would run in a separate thread. I used REACTJS with TailwindCss to display the data from a backend RESTAPI.",
    techStack: [
      { name: "Reactjs" },
      { name: "TailwindCss" },
      ,
      { name: "Java" },
      { name: "Spring" },
      ,
      { name: "Hibernate" },
      { name: "Maven" },
      { name: "MySQL" },
      { name: "JUNIT" },
    ],
    livesite: false,
    demo: "/videos/priceFinderDemo.mp4",
    githubRepo: "https://github.com/SohailMG/price-finder",
    image: "/images/priceFinder.png",
  },
  {
    id: 1,
    name: "Uber Clone",
    description:
      "An Uber app clone using expo , react native with Redux and tailwindcss, Google cloud services are also used for map and directions",
    techStack: [
      { name: "JavaScript" },
      { name: "Reactjs" },
      { name: "Redux" },
      { name: "Google Cloud" },
    ],
    livesite: false,
    demo: "videos/UberClone.mp4",
    githubRepo: "https://github.com/SohailMG/uber-clone",
    image: "/images/UberClone.png",
  },
  {
    id: 2,
    name: "Amazon Clone",
    description:
      "Full stack amazon clone using nextjs for server side rendering of products,orders and basket items, tailwindcss for responsive design, redux for shopping basket functionality, NextAuth authentication with google and stripe for payment and webhooks",
    techStack: [
      { name: "Nextjs" },
      { name: "Reactjs" },
      { name: "Redux" },
      { name: "Google Cloud" },
      { name: "Firebase" },
      { name: "Stripe" },
      { name: "Tailwindcss" },
    ],
    livesite: "https://amazon-clone-iota-liart.vercel.app/",
    demo: false,
    githubRepo: "https://github.com/SohailMG/amazon-clone",
    image: "/images/AmazonClone.png",
  },
  {
    id: 3,
    featured: true,
    name: "Path Finder",
    description:
      "An algorithm visualiser for finding the shortest path using Breath First Search on a 2D Grid",
    techStack: [
      { name: "JavaScript" },
      { name: "Vuejs" },
      { name: "Tailwindcss" },
    ],
    livesite: "https://sohail-pathfinder.netlify.app/",
    demo: false,
    githubRepo: "https://github.com/SohailMG/bfs-visualiser",
    image: "/images/PathFinder.png",
  },
];
