module.exports.schools = [
  {
    name: "Middlesex University",
    prefix: "MDX",
    url: "https://www.mdx.ac.uk/",
    type: "Bsc Computer Science",
    from: "Sep 2019",
    to: "July 2022",
    grade: "First Class Honors",
    topics: [
      "Advanced Web Development with Big Data",
      "UX/UI Design",
      "Mobile Apps Development",
      "Final Year Project",
      "Object-Oriented-Programming with java",
      "Website Development and Applications",
      "Operating Systems & Networking",
      "Software Engineering Management",
      "Algorithms & Data Structures",
    ],
    keyPoints: [
      "Implement, Analyse and compare algorithms using C++.",
      "Managing software source code using version control systems (Git/Github).",
      "Apply automated software testing techniques such as Unit Testing with Jest.",
      "Effectively present and communicate design concepts such as UML class diagrams,wireframes and cloud architecture.",
      "Construct professional quality websites displaying data from large databases using Node.js and advanced JavaScript frameworks such as React and Vue.",
      "Designing complex multi-threaded Java programs using Spring, Hibernate and Maven.",
      "Planning and implementing real-time web applications using WebSockets as well as processing data both locally and in the cloud using AWS.",
      "Demonstrating a sophisticated application of information searching, analytical competency, critical evaluation, writing and communication skills to enable effective documentation and communication.",
      "Demonstrating creative thinking competencies.",
    ],
  },
  {
    name: "Hammersmith & West London College",
    prefix: "WLC",
    url: "https://www.wlc.ac.uk/",
    type: "BTEC National Extended Diploma in IT",
    from: "Sep-2015",
    to: "Jul-2019",
    grade:
      "Pearson BTEC Level 3, National Extended Diploma in IT Awarded |Distinction*,Distinction*,Distinction*",
    topics: [
      "Computer Networks",
      "Human Computer Interaces",
      "Object-Oriented-Programmingm",
      "Computer Graphics",
    ],
  },
  {
    name: "Rooks Heath Secondary School",
    prefix: "RH",
    url: "https://www.rooksheath.harrow.sch.uk/",
    type: "GCSE",
    from: "Jan-2013",
    to: "Jul-2015",
    grade: "English(C), Maths(C) ,Arabic(A*), Sociology (D), Media(B)",
    topics: ["Media", "Sociology", "DT design and technologyird", "IT"],
  },
];
